package com.pojo;

// Generated 6 Aug, 2021 3:02:29 PM by Hibernate Tools 3.4.0.CR1

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer sid;
	private Collage collage;
	private String sname;

	public Student() {
	}

	public Student(Collage collage, String sname) {
		this.collage = collage;
		this.sname = sname;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public Collage getCollage() {
		return this.collage;
	}

	public void setCollage(Collage collage) {
		this.collage = collage;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

}
